### ISSUE TITLE
Aquire MQTT credentials thorugh Supervisor

### ISSUE THREAD

**Issue by LasseSkogland** [net-daemon/netdaemon#1002]
## The problem
Developers/Users needs to enter MQTT details in the config file.

## The proposed solution
It is rather simple to implement.
Code from my project:
```
var hassioToken = Environment.GetEnvironmentVariable("HASSIO_TOKEN");
HASupervisorMqttConfiguration? mqttConfig = null;
if (hassioToken != null) {
    using var http = new HttpClient();
    http.DefaultRequestHeaders.Add("Authorization", hassioToken);
    var res = await http.GetStreamAsync("http://supervisor/services/mqtt").ConfigureAwait(false);
    mqttConfig = await JsonSerializer.DeserializeAsync<HASupervisorMqttConfiguration>(res, JsonContext.Default.Options).ConfigureAwait(false);
}
```
The data returned includes Host, Port, Username and Password (for the addons user)
I don't have the time, yet, to create a pull request for this.

**Comment by skotl** [comment]
Seems a reasonable idea. I presume that `HASupervisorMqttConfiguration` is your own class?

I'd be happy to see a PR and review it.

**Comment by LasseSkogland** [comment]
Yes, that is correct.
For the purpose of documentation, it looks like this:
```
    public sealed class HASupervisorMqttConfiguration {

        public string Result { get; set; } = default!;

        public DataObject Data { get; set; } = default!;

        public sealed class DataObject {
            public string Host { get; set; } = default!;
            public int Port { get; set; } = default!;
            public string Username { get; set; } = default!;
            public string Password { get; set; } = default!;
        }
    }
```
I will look into it when I have the time.

**Comment by helto4real** [comment]
With the latest version of ND there are possible to do detailed configurations to MQTT with the ADD-ON
