### ISSUE TITLE
State changes being triggered multiple times when only a single entity changes

### ISSUE THREAD

**Issue by danpowell88** [net-daemon/netdaemon#104]
## The problem

When a state change occurs and multiple entities have been specified in the source list, the action is called for the number of entities that are in the original as opposed to just the number of entities that actually had a state change 

## Environment

- NetDaemon release with the issue:
- Last working NetDaemon release (if known): Latest dev build
- Operating environment (Home assistant Add-on/Docker/Dev setup): Docker
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

https://github.com/danpowell88/home/blob/master/apps/RoomApp.cs#L103
```c#


Entities(MotionSensors!)
                .WhenStateChange((to, from) => @from?.State == "off" && to?.State == "on" && MotionEnabled)
                .Call(PresenceAction)
                .Execute();
```

## Traceback/Error logs

```txt

```

**Comment by helto4real** [comment]
Closing this issue, we already suspected multiple logging outputs or instances. Please reopen if the problem reoccur
