### ISSUE TITLE
Codegenerator: Add the possibility to pass data to scripts

### ISSUE THREAD

**Issue by helto4real** [net-daemon/netdaemon#1089]
## The problem
We cannot pass data to script calls to the generated scripts in CodeGen.

## The proposed solution
Make a overload to pass custom data.

**Comment by attig78** [comment]
This would be great.

We should also consider doing the same for all the other services that do not support arguments, for example "rest_command".

As I understand it, any service can take service data.

**Comment by helto4real** [comment]
The #1093 should take care of this, both the scripts and other domains that lacks meta data input
