### ISSUE TITLE
Generated service code doesn't support fractional values for numeric arguments

### ISSUE THREAD

**Issue by cdauphinee** [net-daemon/netdaemon#1092]
## The problem
The generated code for services uses `long` as the C# type for service arguments that are defined as numbers. This prevents us from providing fractional values, which is supported by YAML's numeric data type.

The `transition` argument on `light.turn_off` and `light.turn_on` are examples of services where fractional values are desirable: currently, NetDaemon's generated code can only transition a light instantly or over 1 second, which is quite long.

```csharp
public void TurnOff(ServiceTarget target, long? transition = null, object? flash = null)
{
    _haContext.CallService("light", "turn_off", target, new LightTurnOffParameters { Transition = transition, Flash = flash });
}
```

## The proposed solution
Changing the mapped type to `double` seems like a straight forward change. 

```csharp
public void TurnOff(ServiceTarget target, double? transition = null, object? flash = null)
{
    _haContext.CallService("light", "turn_off", target, new LightTurnOffParameters { Transition = transition, Flash = flash });
}
```

`long` can be implicitly converted to `double`, so the change should largely be backwards compatible for users. If there are concerns about breaking compatibility, this could be made a configurable option, but it would require quite a bit of refactoring to make the code gen configuration accessible to the mapper; it and most of its callers are static methods.

## Additional context
I can contribute this change, but wanted to open a discussion in case this has already been considered, or if there was a reason for using `long` in the first place. Also interested in thoughts on changing the default behavior vs. doing the extra refactoring to make it configurable.

**Comment by helto4real** [comment]
What do you think about this @FrankBakkerNl ?
I would say it is reasonable.

**Comment by FrankBakkerNl** [comment]
We already generate a double or a long for service arguments based on the value of the 'step' of that argument in the metadata.

see https://github.com/net-daemon/netdaemon/blob/dff49c896e89888c1e348491424b11297fe55c1a/src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/ServicesMetaData/HassServiceArgumentMapper.cs#L15

```
 NumberSelector s when (s.Step ?? 1) % 1 != 0 => typeof(double),
NumberSelector => typeof(long),
```

I see that for this specific service attribute there is no step in the metadata, I would want to see what HA renders in the developer tools UI for this argument. If the HA UI allowes fractions in case the setp is null, we could change this

```
  "turn_off": {
      "name": "Turn off",
      "description": "Turn off one or more lights.",
      "fields": {
        "transition": {
          "filter": {
            "supported_features": [
              32
            ]
          },
          "selector": {
            "number": {
              "min": 0,
              "max": 300,
              "unit_of_measurement": "seconds"
            }
          },
          "name": "Transition",
          "description": "Duration it takes to get to next state."
        },
        "flash": {
          "filter": {
            "supported_features": [
              8
            ]
          },
          "advanced": true,
          "selector": {
            "select": {
              "options": [
                {
                  "label": "Long",
                  "value": "long"
                },
                {
                  "label": "Short",
                  "value": "short"
                }
              ]
            }
          },
          "name": "Flash",
          "description": "Tell light to flash, can be either value short or long."
        }
      },
```
