### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ludeeus** [net-daemon/netdaemon#123]
## Environment

- NetDaemon release with the issue:
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
.

**Comment by helto4real** [comment]
Good point

**Comment by ludeeus** [comment]
Right?
