### ISSUE TITLE
Unable to debug service call issues

### ISSUE THREAD

**Issue by danpowell88** [net-daemon/netdaemon#125]
When a service call fails its impossible to tell what service call it was

```
[11:18:59 WRN] Non successful unwaited result for command call_service: code(unknown_error), message: Communication error
```

**Comment by helto4real** [comment]
Actually you can do this. HASS_LOG_LEVEL=trace

**Comment by helto4real** [comment]
Better logging is now provided default of failed service calls in https://github.com/net-daemon/netdaemon/commit/755c02b9ae572861e1b58bceaf6c27956b491f64
