### ISSUE TITLE
Load apps from multiple assemblies

### ISSUE THREAD

**Issue by BeeHiveJava** [net-daemon/netdaemon#139]
## The problem
Apps cannot be loaded from an assembly other than the entry assembly. It's not a huge problem, but I think it's a good idea to give developers the freedom to apply an architecture as they see fit. For example, I'd love to have my apps in a different project (assembly) and have my yaml files point to them.

## The proposed solution
As you can see from [here](https://github.com/net-daemon/netdaemon/blob/3ca79e64c22f2de6fa1f02b41d34cc23d06e5a5a/src/DaemonRunner/DaemonRunner/Service/App/DaemonCompiler.cs#L72) the assembly to search from is currently hardcoded. Perhaps this could be expanded to search in all loaded assemblies. The yaml files can still be present in the same */apps* directory.

[GetReferencedAssemblies](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getreferencedassemblies?view=netcore-3.1) could be used, but be aware that it only loads the assemblies if types are actually being used. See [this stackoverflow answer](https://stackoverflow.com/a/2242007)

## The alternatives
As an alternative, you can create a wrapper that inherits from your real app like so:

```CS
namespace Automation.Terminal.Apps
{
    public class TestAppWrapper : TestApp
    {
    }
}
```

```CS
namespace Automation.Apps
{
    public class TestApp : NetDaemonRxApp
    {
        public override Task InitializeAsync()
        {
            Console.WriteLine("INITIALIZED");
            return Task.CompletedTask;
        }
    }
}
```

Notice that the real app lives in a different assembly.

**Comment by helto4real** [comment]
What you can do as a work-around is to provide the whole csproj file yourself using the HASS_RUN_PROJECT_FOLDER flag of container. See https://netdaemon.xyz/docs/started/installation#evironment-variables-you-can-set

This allows you to use the actual csproj file you are using developing and use additional nuget packages. Just point to the csproj file in the same folder as "apps"

**Comment by BeeHiveJava** [comment]
Thanks for the tip but I don't understand this entirely. I'm running NetDaemon as a standalone application using environment variables to configure it. I can't quite see where that environment variable is used (nor can I figure out how to use it). From [here](https://github.com/net-daemon/netdaemon/blob/0f96b5104ad72a8c1d984d70ac98574412d3b9f4/src/DaemonRunner/DaemonRunner/Service/RunnerService.cs#L51) it can be seen it's set as a fallback when using a json configuration file without specifying a project folder.

Is this maybe used only in Docker?

**Comment by Trektus** [comment]
Same problem here. I have set the project_folder: /config/netdaemon in the NetDaemon-AddOn-Configuration. The project file  \config\netdaemon\daemonapp.csproj contains some additonal PackageReference-Entries (Microsoft.ML ...) but I get compile errors like "error CS0234: The type or namespace name 'ML' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)"

Thanks in advance.

**Comment by helto4real** [comment]
You need to set the NETDAEMON__PROJECTFOLDER=/config/netdaemon if you run docker 
or project_folder: /config/netdaemon if you run add-on. This way netdaemon is poitning to your csproj file instead of the hidden on.
Think I need to document this better.
@Trektus @BeeHiveJava

**Comment by helto4real** [comment]
There are now 3 different deployment scenarios.
1. Default dynamic compilation (safe and no extra dependecies allowed)
2. Run the project with dotnet run (all dependecies allowed)
3. Run a published project (all depdendecies allowed)
See [here](https://netdaemon.xyz/docs/started/installation#advanced-add-on-configurations) for add-ons and [here](https://netdaemon.xyz/docs/started/installation#advanced-add-on-configurations) for docker.
I think there are options that make this scenario possible so I closing this now cause the added complexity and security issues is not worth for the dynamic case for now.
