### ISSUE TITLE
Provide a way to get dependencies / services in apps

### ISSUE THREAD

**Issue by BeeHiveJava** [net-daemon/netdaemon#140]
## The problem
Apps are currently instantiated using the [CreateInstance](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netcore-3.1) method in ```Activator```, as you can see [here](https://github.com/net-daemon/netdaemon/blob/3ca79e64c22f2de6fa1f02b41d34cc23d06e5a5a/src/Daemon/NetDaemon.Daemon/Daemon/Config/YamlConfig.cs#L78). This prevents the usage of dependency injection using a container such as [IServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider?view=netcore-3.1).

## The proposed solution
Use the [ActivatorUtilities](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilities?view=dotnet-plat-ext-3.1) provided by Microsoft to provide a dependency container when instantiating apps, like so:

```CS
var serviceProvider = null; // An instance of IServiceProvider can be injected in the constructor.
var netDaemonApp = (INetDaemonAppBase?)ActivatorUtilities.CreateInstance(serviceProvider, netDaemonAppType);
```

Also there would have to be a way to access the container to register your dependencies. I think this could be a pretty big change, but it would aid building of complex apps.

## The alternatives
Alternatively a property or method to get dependencies / services can be exposed on the ```INetDaemonAppBase``` class (just like ```IHttpHandler```.

**Comment by helto4real** [comment]
This is an interesting idea. I will check it out what this means for the design

**Comment by BeeHiveJava** [comment]
I just remembered that it's better to provide a method to get services (or provide a property exposing the the `IServiceProvider`) rather than using constructor injection. Because if you register transient dependencies and the NetDaemon apps are actually singletons / scoped, then the transient dependencies become effectively singleton / scoped.

I'll have a crack at this.

**Comment by helto4real** [comment]
Cool. Thanks. @BeeHiveJava are you in the Discord group. Let me know your user name so I can upgrade your status to contributor :) If you want to.

**Comment by asherw** [comment]
Had a small chat to Dan today (hes on discord) around this.

It would be nice to provide a lifetime scope / component context (what ever the .net core ioc piece is called) during state changes and actions to be able to resolve services rather than having everything singleton or newing them up manually.

**Comment by helto4real** [comment]
@asherw so lets discuss details on discord or make a feature issue that describes this. Sounds interesting.

**Comment by helto4real** [comment]
@asherw @BeeHiveJava are any work being done on this one? Is it still relevant to instance apps using other methods?

**Comment by helto4real** [comment]
Closing this and open new issue to cover eventual constructor injection
