### ISSUE TITLE
discord or similar chat? 

### ISSUE THREAD

**Issue by addd45** [net-daemon/netdaemon#18]
Not an issue, rather a question or suggestion. I'm really interested in utilizing this daemon, but as it's still in early stages, it would be awesome to get a community started so people can learn the ins and outs and learn some advanced features, etc. 

  I know  I personally have some questions about how to accomplish certain tasks. 

Love the project!

**Comment by helto4real** [comment]
I created a Discord server

https://discord.gg/K3xwfcX
