### ISSUE TITLE
"HASSCLIENT_BYPASS_CERT_ERR" variable is not working anymore

### ISSUE THREAD

**Issue by LiranSX** [net-daemon/netdaemon#201]
## The problem
in 0.9.6 version there was support for bypassing self signed certificate errors by specifying the certificate's thumbprint as an environment variable named "HASSCLIENT_BYPASS_CERT_ERR". it doesn't work anymore and netdaemon docker app cannot connect to wss:// address of home assistant.

## Environment
currently using version 0.15.0
last working in version 0.9.6

**Comment by helto4real** [comment]
It was working closing this
