### ISSUE TITLE
Improve developer experience using custom nuget packages and other references

### ISSUE THREAD

**Issue by helto4real** [net-daemon/netdaemon#248]
## The problem
NetDaemon supports using custom projects that include custom dependecies. It is not well documented how this should be done and also we need to consider security in this case. The default should be sandboxed and secure but also alow the flexibility to add more features and dependecies if you want to.

## The proposed solution
- [ ] Default usage of custom project file if it is included in same path as `apps` 
- [x] Specifically allow NetDaemon to use the included project file'
- [x] To be able to publish projects and deploy them pre-compiled
- [ ] Document in netdaemon.xyz docs site
- [ ] Provide downloadable examples in awesome_netdaemon repo

## Additional context
We need to make sure it is secure by default and it is a by choice NetDaemon uses the provided file

**Comment by quettih** [comment]
today netdaemon takes all the  *.cs  file in apps folder and **load them as assembly** into memory.
what about **loading also  DLLs** with the same approach ?
if dll is signed with a certificate, you can consider it "secure" ... but also gie possibility, by  a flag,  to   "load_unsigned_dll".
once in memory, your  .cs  code can use it...

**Comment by helto4real** [comment]
> today netdaemon takes all the *.cs file in apps folder and **load them as assembly** into memory.
> what about **loading also DLLs** with the same approach ?
> if dll is signed with a certificate, you can consider it "secure" ... but also gie possibility, by a flag, to "load_unsigned_dll".
> once in memory, your .cs code can use it...

Yes I been considering this option. I am a bit scared of the complexity and security. I will consider this for the future. For now I will go with making the experience better by just allowing copying the whole project to NetDaemon folder and it will work out of the box. I will also keep the setting for specify specific project paths if you have a complex project structure and wants to point the the NetDaemon service project as startup.

**Comment by helto4real** [comment]
I also added an option to this feature issue to do deployments using publish the project.

**Comment by quettih** [comment]
> > today netdaemon takes all the *.cs file in apps folder and **load them as assembly** into memory.
> > what about **loading also DLLs** with the same approach ?
> > if dll is signed with a certificate, you can consider it "secure" ... but also gie possibility, by a flag, to "load_unsigned_dll".
> > once in memory, your .cs code can use it...
> 
> Yes I been considering this option. I am a bit scared of the complexity and security. I will consider this for the future. For now I will go with making the experience better by just allowing copying the whole project to NetDaemon folder and it will work out of the box. I will also keep the setting for specify specific project paths if you have a complex project structure and wants to point the the NetDaemon service project as startup.



> I also added an option to this feature issue to do deployments using publish the project.

I'm ready for any kind of  test :-)

**Comment by helto4real** [comment]
This is fixed for now. I will lookinto how to run NetDaemon apps in isolation and be distributable with HACS for example. This requires alot of re-thinking.
