### ISSUE TITLE
Entity Interfaces for Helper types

### ISSUE THREAD

**Issue by Rogardo** [net-daemon/netdaemon#279]
I build my Interface with the Node-Red Dashboard and use a lot of helpers for invoke my Netdaemon methodes. But I miss the Interfaces for 'Number' (set_value) and Time picker (time, date, datetime etc.)

Is it possible to add the Interfaces to your libary?

I know it's always possible to handle it with CallService, but would be cool to use the direct service methode.

**Comment by helto4real** [comment]
Yea I will takt this into consideration. My plan is to extend number of supported entities. Thanks for reporting the request @Rogardo

**Comment by FrankBakkerNl** [comment]
The new HassModel Codegen will generate all the services for these entities
https://netdaemon.xyz/docs/hass_model/hass_model_codegen
