### ISSUE TITLE
HasDevice.model can be a number for a lifx device

### ISSUE THREAD

**Issue by DTTerastar** [net-daemon/netdaemon#296]
## The problem

Got exception over and over and made no progess in app:

System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.

I tracked it down to a model number coming back as a number not a string.  I delete my LIFX device and it started working again.

Snippet from trace that caused the issue: 

{"config_entries": ["43d54cc19bb1f903d73bcdcac37047a8"], "connections": [["mac", "d0:xx:xx:xx:xx"]], "manufacturer": "LIFX", "model": 87, "name": "LIFX White 5F1E8A", "sw_version": 3.7, "entry_type": null, "id": "18c43690bd6845891b5e5b92718c9d17", "identifiers": [["lifx", "d0:xx:xx:xx:xx"]], "via_device_id": null, "area_id": "nick_s", "name_by_user": null, "disabled_by": null}, 

See how model is a number?  The HassDevice expects a string for model.

## Environment

version 21.00.0
Docker

- NetDaemon release with the issue:
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by suddenelfilio** [comment]
HassDevice.Model = string where the JsonConverter will try to convert the model: 87 to an int.

I think there are two possibilities to fix this (also this in the HassClient project)

-  update the JsonSerializerOptions.NumberHandling = JsonNumberHandling.WriteAsString => but this will do it for all numbers
- Create a Custom JsonConverter<string> which will read the token and see if it is a number to convert to a string and decorate the Model property like so:
` [JsonPropertyName("model")] 
  [JsonConverter(typeof(StringConverter))]
  public  string? Model { get; set; }`

I personally like the opt-in principle of the second option.

**Comment by suddenelfilio** [comment]
I've reported it in the net-hassclient repo https://github.com/net-daemon/net-hassclient/issues/102

**Comment by suddenelfilio** [comment]
Hey @DTTerastar can you try with the dev release? It includes a fix for this issue.

**Comment by DTTerastar** [comment]
Will do

**Comment by suddenelfilio** [comment]
I believe it is even released, will check with @helto4real

**Comment by helto4real** [comment]
Yes it is now released @DTTerastar @suddenelfilio

**Comment by DTTerastar** [comment]
Sorry, LIFX isn't cooperating.  I haven't been able to re-add it.

**Comment by helto4real** [comment]
So its still an issue? Should we reopen this then?

**Comment by DTTerastar** [comment]
Sorry, I'm saying I can't get LIFX to fail in the same way again.  NetDaemon is working fine.  Carry on.

**Comment by helto4real** [comment]
Ohh thanks cause it is fixed :) makes sense
