### ISSUE TITLE
Entity generator produces wrong code in file "_EntityExtensionsRx.cs.gen" 

### ISSUE THREAD

**Issue by gimi87** [net-daemon/netdaemon#321]
## The problem

Entity generator produces wrong code in file "_EntityExtensionsRx.cs.gen"

## Environment

- NetDaemon release with the issue: 21.6.0-beta, 21.8.0-beta
- Last working NetDaemon release (if known): 21.5.1-beta
- Operating environment (Home assistant Add-on/Docker/Dev setup): Dev setup (from [https://github.com/net-daemon/netdaemon-app-template](url))
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#
...

public partial class InputSelectEntity : NetDaemon.Common.Reactive.Services.RxEntityBase
{
    public InputSelectEntity(INetDaemonRxApp daemon, IEnumerable<string> entityIds): base(daemon, entityIds)
    {
    }

    public void Reload(dynamic? data = null)
    {
        CallService("input_select", "reload", serviceData, False);
    }
...

```

## Traceback/Error logs

```txt
Error	CS0103	The name 'serviceData' does not exist in the current context
Error	CS0103	The name 'False' does not exist in the current context
```

**Comment by helto4real** [comment]
Fixed in #322
