### ISSUE TITLE
Missing section https://netdaemon.xyz/docs/started/installation#deploy-your-apps

### ISSUE THREAD

**Issue by wojciechczyz** [net-daemon/netdaemon#333]
## The problem

This section of documentation is missing.
It would likely speed up making first steps with NetDaemon

## Environment

- NetDaemon release with the issue:
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by helto4real** [comment]
Thanks for reporting but not sure what section you are referring to?

**Comment by wojciechczyz** [comment]
deploy-your-apps it leads nowhere yet is present in document

**Comment by helto4real** [comment]
Ahh ok got it, thanks @wojciechczyz

**Comment by helto4real** [comment]
fixed
