### ISSUE TITLE
add-on images are not removed after an upgrade

### ISSUE THREAD

**Issue by quettih** [net-daemon/netdaemon#336]
## The problem

After upgrading the netdaemon addon, the previous images are not removed and they allocate a lot of space

## Environment
- NetDaemon release with the issue: 21.08.1
- Last working NetDaemon release (if known): N/A
- Operating environment (Home assistant Add-on/Docker/Dev setup): RPI 4 Home Assistant Core 2021.2.3 (it is old I know)
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

 upgrade the addon to a newer version
open portainer and search for "netdaemon" (see picture)
the old images are no longer used but they allocates spaces

```c#

```

## Traceback/Error logs

 no errors
![old images](https://user-images.githubusercontent.com/34207189/111679611-a3e62780-8821-11eb-84f5-219c199181b9.jpg)

```txt

```

## Additional information
does the fix will remove all the previous versions or just the "previous one" ?

**Comment by helto4real** [comment]
The needed meta data is now provided in the docker images for this to work.
