### ISSUE TITLE
Generated Entities Doc Wrong?

### ISSUE THREAD

**Issue by omayhemo** [net-daemon/netdaemon#409]
Following the instructions here:
https://netdaemon.xyz/docs/api/api_gen_entities

I have updated my appsettings.json with the generate_entities:true. 
I checked the box for generate entities on the add-on.

When I restart the add-on I get a single file:
_EntityExtensionsRx.cs.gen

The namespace Netdaemon.Generated.Reactive is not available (not even after a build), nor is the GeneratedAppBase.  None of the entities are visible.  I tried renaming the .gen file to just .cs, to no avail.

It appears the documentation maybe out of date from the beta branch.  
What am I doing wrong?

Additionally, I'm getting exceptions at runtime about once every several seconds, with just the default template with entities properly changed to something I actually have in the HelloWorld app:

```
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in NetDaemon.Daemon.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Private.CoreLib.dll

```

**Comment by helto4real** [comment]
You need to rename it from .gen to .cs. This is so new generated code does not interfere with existing automations.

**Comment by omayhemo** [comment]
I did that, the namespace is still not being picked up by VS.  Even ran a restore, and it's just ignored.

**Comment by helto4real** [comment]
Hmm maybe something else is changed that are not correct in docs. Please check the namespace of generated code please. By the way we have discord server for support too.
https://discord.gg/K3xwfcX

**Comment by omayhemo** [comment]
thanks, I'll swing over to discord

**Comment by omayhemo** [comment]
Set Build Action to C# Compiler and its working now.
