### ISSUE TITLE
Run only specific apps during development

### ISSUE THREAD

**Issue by FrankBakkerNl** [net-daemon/netdaemon#411]
## The problem
When working on a Netdeamon app in Development you want to run it against a live Hass instance. Usually you have other apps in the same solution that you do not want to run while debuging this single app.

## The proposed solution
Add a  config setting that will allow running just a single app. We can add this to the config.develooment.json of the template application.

It would also be nice If you could select the app to run while developing by adding an attribute to the class like some testframeworks do, like [Focus] if at least one app has this set AND the setting is present in the config, only this app will be loaded.

**Comment by helto4real** [comment]
Also the [Focus] should only be active if in development environment is active like: 
```csharp
if (env.IsDevelopment())
{
    // the logic of [focus]
}
```

**Comment by FrankBakkerNl** [comment]
A so we do not need a new setting at all, just the attribute. That's nice
