### ISSUE TITLE
Feature: Website showing app instance data

### ISSUE THREAD

**Issue by helto4real** [net-daemon/netdaemon#44]
First MVP just to show running instances .

Next possible features
- enable/disable/restart individual apps
- Check what entities being used and their current state
- Automatic log of all actions happening in an app
- Edit individual app settings in GUI

**Comment by isabellaalstrom** [comment]
Would be very much appreciated!

**Comment by danpowell88** [comment]
Would be good to also see any schedules/timers and when they are due to fire next

**Comment by ludeeus** [comment]
https://github.com/net-daemon/admin

**Comment by helto4real** [comment]
Closing this and we do specific requests on the released GUI
