### ISSUE TITLE
Make NumericEntityState TryParse use invariant culture

### ISSUE THREAD

**Issue by Ed55** [net-daemon/netdaemon#561]
Example:
A huminity sensor reads 505 on my German developement system (Windows PC VS2020) and 50.5 on my production system (Synology Docker).
Probable cause "Parameter s is parsed using the formatting information in a NumberFormatInfo object initialized for the current system culture."

**Comment by helto4real** [comment]
Thanks for the suggestion. We should have a solid story for the culture problem. Not sure this are not creating same problem as it creates. Maybe some way to allow the user to set the culture and use neutral as default. What you think @FrankBakkerNl ?

**Comment by FrankBakkerNl** [comment]
Hmm this is kind of embarrassing, just did not pass an invariant culture in the Double.TryParse, looks like an easy fix

**Comment by Ed55** [comment]
Yepp, sorry, just one day with NetDaemon by now.
Having had a look into the source meanwhile, my header is missleading.
In NumericEntity the double.TryParse should use invariant culture ....
I think :-)

**Comment by FrankBakkerNl** [comment]
Yes indeed it should be culture-UN-aware. At first from the title I thought you were actually requesting the opposite which was a NO GO of course ;-)

**Comment by Ed55** [comment]
Thanks Frank, and sorry for the misleading title, I should have "smelled" the bug even without the source ;-)

**Comment by FrankBakkerNl** [comment]
Fixed
