### ISSUE TITLE
Restart netdaemon when network connection to HA fails.

### ISSUE THREAD

**Issue by PhilippCh** [net-daemon/netdaemon#593]
## The problem
When communicating with Home Assistant on a different host than the one ND is running in, when network connectivity is lost (e.g. upon router restart, lost internet connection, etc.), ND throws a WebSocket exception that it is currently unrecoverable from. The service keeps running, but the HA WebSocket connection is never reopened, even after network connectivity has been restored.

## The proposed solution
Catch Websocket Exceptions to HA and implement a simple retry mechanism (that maybe waits until the system reports network connectivity again).

**Comment by helto4real** [comment]
Thanks for reporting, This is fixed in https://github.com/net-daemon/netdaemon_v2/releases/tag/22.1.3
