### ISSUE TITLE
Feature Request: Make the template repo a dotnet template

### ISSUE THREAD

**Issue by 333fred** [net-daemon/netdaemon#619]
## The problem

Currently, the template repo is a git repo that users need to clone and then edit. This is a bit annoying for a couple of reasons:
* To rename projects and adjust default namespaces, a few manual edits are needed.
* The repo comes with a git history the user probably doesn't want.

## The proposed solution

The template repo could be migrated to a custom template: https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates. As a further step (suggested by @FrankBakkerNl on discord) file templates could be added as well for new individual automations.

## The alternatives

Leaving things as they are.

**Comment by helto4real** [comment]
This is a great idea actually. Maybe when moving to V3 of the NetDaemon runtime this could be introduced in a own repo . What you think @FrankBakkerNl ?

**Comment by helto4real** [comment]
Done:
dotnet new --install JoySoftware.NetDaemon.Templates.Project
dotnet new nd-project
