### ISSUE TITLE
Calling AddAppFromType before AddAppsFromAssembly only discovers the app in the first call

### ISSUE THREAD

**Issue by BeeHiveJava** [net-daemon/netdaemon#620]
## The problem

Whenever I setup my project, and I somewhere end up calling `AddAppFromType` before I call `AddAppsFromAssembly`, it will only resolve the app specified in `AddAppFromType`. This is probably because [this code](https://github.com/net-daemon/netdaemon/blob/0e4e6fdd7e19ac3445488e2db1d3045de0980efb/src/AppModel/NetDaemon.AppModel/Common/Extensions/ServiceCollectionExtension.cs#L50) checks whether there already is an `IAppResolver` registered. And there is, because `AddAppFromType` adds a `SingleAppResolver`. This now fails to add the required `AppTypeResolver`, which uses the registered `IAssemblyResolver`.

## Environment

- NetDaemon release with the issue: 22.3.0
- Last working NetDaemon release (if known): -
- Operating environment (Home assistant Add-on/Docker/Dev setup): Docker / Dev
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

1.
```c#
    public static IServiceCollection AddAppDeps(this IServiceCollection services) =>
        services
            .AddAppFromType(typeof(<AppType>))
```

2.
```c#
    public static IServiceCollection AddAssemblyDeps(this IServiceCollection services) =>
        services
            .AddAppsFromAssembly(typeof(<AppType>).Assembly);
```

## Traceback/Error logs

```txt

```

**Comment by helto4real** [comment]
Yes you are right this is a bug indeed. The intended logic was to check so appmodel and type resolver are not registered in DI more than once.
