### ISSUE TITLE
Add codegen as local tool to template

### ISSUE THREAD

**Issue by FrankBakkerNl** [net-daemon/netdaemon#679]
## The problem
The codegen the user has installed globally  can be out of sync with the hasdmodel packages. Resulting in comoile errorrs.

## The proposed solution
Setup the codegan as a local tool in the template

Update the docs for installing odegan.
Update dics for updating nugets and tool

**Comment by helto4real** [comment]
@FrankBakkerNl we can close this now right?

**Comment by FrankBakkerNl** [comment]
Not Sure I think I created a PR for this but I think it was not merged yet, not sure why, maybe it needed some more work

**Comment by helto4real** [comment]
This is done
