### ISSUE TITLE
Generated code looses attributes that are not present when running the nd-codgen tool.

### ISSUE THREAD

**Issue by FrankBakkerNl** [net-daemon/netdaemon#685]
## The problem

The generated code has a class with properties that match the attributes for tje entities in each domain. Some entities will not always have all attributes present. eg a light entity only has a brightness attribute when it is turned on. As a result when re-generating the code while all lights are off the generated LightEntityEttributes class will not have a Brightness property. Any used code that uses this property will then fail to compile.
## Environment

22.6.3

## Traceback/Error logs

```txt

```

**Comment by helto4real** [comment]
Yea we might need to handle this by saving attributes in some file so we at least keep attributes discovered in previous scans

**Comment by FrankBakkerNl** [comment]
I have a draft PR up for this that will solve the most common cases (lights off during codegen). What specific entities / attributes did you have problems with?

**Comment by Tsuy89** [comment]
Good to hear there is something in the pipeline! My case was also the brightness attribute, same as the example.
