### ISSUE TITLE
ProximityEntity state should be numeric

### ISSUE THREAD

**Issue by rumbu13** [net-daemon/netdaemon#715]
## Problem: State for ProximityEntity is a string
On the contrary, it is always measured in km, miles or other distance units. 

 ## Solution: Alter Code Generator
Use `NumericEntityState` to define `ProximityEntity`:

```csharp
public record ProximityEntity : Entity<ProximityEntity, NumericEntityState<ProximityAttributes>, ProximityAttributes>
```

## More Info

Reference: [Proximity Integration](https://www.home-assistant.io/integrations/proximity/)

**Comment by helto4real** [comment]
I guess we need to handle proximity separately in codegen @FrankBakkerNl ?

**Comment by FrankBakkerNl** [comment]
We basically have 3 types of domains now
1 always string (default)
2 always numeric, like input_number
3 only numeric if there is a unit of measurement attribute

Which of these would fit best here?

**Comment by rumbu13** [comment]
I would vote for 3, since ```unit_of_measurement``` is optional, but if not set, it is considered ```km``` and added by default to the  state attributes.

---

Another one: ```CounterEntity``` state should also be numeric. Basically it's just an ```input_number``` where the value cannot be set but can be incremented, decremented or reset.

```CounterEntity``` will fit best in the 2nd category.

Reference: [Counter Integration](https://www.home-assistant.io/integrations/counter/)

```csharp
public partial record CounterEntity : Entity<CounterEntity, NumericEntityState<CounterAttributes>, CounterAttributes>
```

**Comment by rumbu13** [comment]
New one: ```InputDatetimeEntity```  state should be DateTime?

References:  [InputDatetime Integration](https://www.home-assistant.io/integrations/input_datetime/)
