### ISSUE TITLE
Removing unnecessary ConfigureAwait

### ISSUE THREAD

**Issue by ThomasWetzel** [net-daemon/netdaemon#740]
## The problem
A console application in .Net 6 has no synchronization context. Removing the "ConfigureAwait" calls makes the code easier to read.

## The proposed solution
  - Would you mind removing the ConfigureAwait calls from the template?
  - Do you need help for this task?

**Comment by skotl** [comment]
I’m not sure of your use case - the template project is intended to be deployed as a class library that will be called by the netdaemon integration so, in that case, there is a sync context and ConfigureAwait is appropriate. 
Are you building a standalone console app to call into Netdaemon or home assistant?

**Comment by ThomasWetzel** [comment]
Hi Scott,

Thanks for getting back to me.
I'm very sorry, yes, you are right.

Indeed I want to build a standalone console app where I can use my preferred DI container (SimpleInjector) and have full control over the system.

Finally this is hosted in my cubernetes cluster. :-)

I think we can close this issue.

There are many possibilities to extend this great project - but this is an other story (issue). ;-)

Thank you so much for this project!

Thomas
