### ISSUE TITLE
Implement IEnumerable on  XyEntities 

### ISSUE THREAD

**Issue by geeForceOne** [net-daemon/netdaemon#745]
## The problem
I would like to be able to enumerate through entities. 

## The proposed solution
Implement IEnumerable on XyEntities like CoverEntities etc. (or other ways to make the entities  enumerable) .

**Comment by helto4real** [comment]
You can allready do this injecting

**Comment by helto4real** [comment]
> true, but the type is `Entity`. It's just a nice to have, but it would be very sexy to do:
> 
> ```
> foreach(var cover in _entities.Cover)
> {
>    // do strongly typed things like 
>   cover.StopCover();
> }
> ```

Got ya

**Comment by phillipsawyer** [comment]
Oh yeah! I was just about to start working on a solution that uses reflection so I can dim all the lights in my house. I think I will attempt to implement this.
