### ISSUE TITLE
Provide advice on HomeAssistantGenerated.cs, commit or not

### ISSUE THREAD

**Issue by LordMike** [net-daemon/netdaemon#766]
Hey,

I'm very pleased to see a .NET wrapper for HA stuff - looking forward to seeing if I should migrate my MQTT stuff over to this :)

I did find that you generate a file with existing entities in HA, `HomeAssistantGenerated.cs`, which is very cool. I did initially read it was "for intellisense", but when I actually found one of these files in an example app, I found that it contains code that is needed to operate, as in it has entities by id - so you can do `Lights.MyLight01.TurnOn()` or whatever.

I initially thought this file was not for checkin, but I just saw an example app that had this file checked in with internals from their HA setup - such as the makes and models of phones, the type of network equipment in use (f.ex. Ubiquiti), the names of the people (`person.xyz`) and so on.

This is a lot of possibly personal information.

Could you tighten up the advice on this file, if it should be committed or not - or at least advise on what it contains?

* [These docs](https://netdaemon.xyz/docs/v2/hass_model/hass_model_codegen) just explain that the file exists and "makes it possible to navigate all Entities and Services using intellisense."

**Comment by FrankBakkerNl** [comment]
I do check it into my private repo. I also have a public repo that has a subset of my code for privacy reasons. In the public repo I don't commit this file because it has a list of all my entities, some of which i consider 'privacy sensitive'

**Comment by helto4real** [comment]
Please use discussions or even better the Discord channel for asking questions. This is only for reporting bugs. https://discord.gg/zCV2GjRXzh

Closing this here.
