### ISSUE TITLE
This is a fake bug

### ISSUE THREAD

**Issue by helto4real** [net-daemon/netdaemon#77]
I have a problemt that I need to write bots and test issues that are fake bugs

## Environment

- NetDaemon release with the issue: 0.2.3
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
NO!
This is not fake...
pls fix!
