### ISSUE TITLE
Referencing TRUSTED_PLATFORM_ASSEMBLIES

### ISSUE THREAD

**Issue by grisia** [net-daemon/netdaemon#771]
## The problem

Not all framework classes are available. Because of missing references

## The proposed solution

Referencing the TRUSTED_PLATFORM_ASSEMBLIES might help

## Additional context

[mod_reference_all_framework_asemblies.patch.txt](https://github.com/net-daemon/netdaemon/files/9890868/mod_reference_all_framework_asemblies.patch.txt)

**Comment by helto4real** [comment]
Than you for your suggestion. The way you suggest code changes on GitHub is to make a pullrequest with the changes not sending them as files. That is also a security issue. You will find instruction on google how to do it. Thanks!
