### ISSUE TITLE
JsonIgnoreCondition.WhenWritingNull to EntityCreationPayloadHelper

### ISSUE THREAD

**Issue by grisia** [net-daemon/netdaemon#772]
## The problem

`MqttEntityManager CreateAsync` generates json where null values are passed.
I use a general class for `additionalConfig` and I always have to set all parameters explicitly. Json with `retain: null` ends with an error entry in the home assistant.

## The proposed solution

Add `JsonSerializerOptions` with `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull` to `EntityCreationPayloadHelper`

## Additional context

[mod_json_ignore_null.patch.txt](https://github.com/net-daemon/netdaemon/files/9890911/mod_json_ignore_null.patch.txt)

**Comment by helto4real** [comment]
Please provide a pull request so we can review and test the solution properly. We will not accept files this way. Thanks for contributing.
