### ISSUE TITLE
Add IsLocked and IsOpen extensions for lock generation

### ISSUE THREAD

**Issue by dakahler** [net-daemon/netdaemon#794]
The generated LockEntityExtensionMethods is missing IsLocked and IsOpen

Adding these would be handy for code tidyness

**Comment by FrankBakkerNl** [comment]
Not sure what exactly you mean here. My guess is you mean something like the IsOn() and IsOff() we have for Entity and EntityState?

```
public static bool IsOn(this EntityState? entityState) => string.Equals(entityState?.State, "on", StringComparison.OrdinalIgnoreCase);
```

The generated extension methods we currently have are for calling services and are based on metadata provided from HA. I think generating this for locks would require special knowledge in the codegen about specific entity types which we currently try to avoid.

Adding these extensions in your own code ofcourse would be quite simple

**Comment by dakahler** [comment]
Ah, I didn't realize these came from metadata. Makes sense.
