### ISSUE TITLE
Home Assistant disconnected due to home assistant closed the connection

### ISSUE THREAD

**Issue by omayhemo** [net-daemon/netdaemon#804]
## The problem
Having just updated to 2022.12.0 HASS, my Netdaemon instance completely stopped working with no code changes.  I went through and made sure I was on all the latest version of ND.  Having no luck, I nuked everything and started from scratch with a fresh basic template app with no code changes or any other additions, enhancements or changes for what amounts to months.  But HA still disconnects the websocket immediately with the following

```
[13:10:14 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant
[13:10:15 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to home assistant closed the connection, connect retry in 30 seconds 
```

## Environment
I'm on NUC.  2022.12.0 HASSOS.  I'm maybe your first adopter.  I'm using the latest dependencies for ND and on the latest version of HASSOS.

- NetDaemon release with the issue: 22.44.0
- Last working NetDaemon release (if known): 
- Operating environment (Home assistant Add-on/Docker/Dev setup): Add-on
- Link to integration documentation on our website: https://netdaemon.xyz/docs/v3

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs
```
[13:10:14 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Successfully connected to Home Assistant
[13:10:15 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to home assistant closed the connection, connect retry in 30 seconds 
```

**Comment by omayhemo** [comment]
I had already setup LogLevels at Trace, no further logging is ever reported once the socket has been forced closed by HA.
I hope to have time to tinker toward the end of the year.  But right now, I don't have a lot of free time at this time and had to implement native automation in ND's place during this down time.

**Comment by helto4real** [comment]
It is hard to help you with no other information than this. I never experienced or heard any other user have this issue. We need those logs from HA as I suggested. I will close issue if I do not get more to go on. Sorry.

**Comment by omayhemo** [comment]
Understood. I just don’t have time ATM, sadly.
