### ISSUE TITLE
See the template v3 branch for examples how to use it. - link is broken

### ISSUE THREAD

**Issue by wojciechczyz** [net-daemon/netdaemon#814]
## The problem
On main project page:
https://github.com/net-daemon/netdaemon
text has link broken
"See the template v3 branch for examples how to use it". - link is broken

## Environment

- NetDaemon release with the issue:
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

**Comment by helto4real** [comment]
Is this to the example app that you are refering to? I will soon fix that. I need to remove some security issues. Thanks for pointing that out.

**Comment by helto4real** [comment]
I now fixed it and made it public again
