### ISSUE TITLE
kill bot with die

### ISSUE THREAD

**Issue by helto4real** [net-daemon/netdaemon#82]
## Example code
```c#
// Insert any example code here that will help describe your requests

```

## Additional information

> Added by Discord user Ludeeus

**Comment by helto4real** [comment]
No closing this cause it is way to funny seeing you being annoyed

**Comment by ludeeus** [comment]
Hey!

**Comment by helto4real** [comment]
Nerd!

**Comment by ludeeus** [comment]
Takes one to know!

**Comment by helto4real** [comment]
Ok maybe you got a point there but still...
