### ISSUE TITLE
Potential duplicate entities after CodeGen normalization 

### ISSUE THREAD

**Issue by mutzl** [net-daemon/netdaemon#830]
CodeGeneration can lead to duplicate entities.

`light.hue_ambiance_spot_1_1`
and
`light.hue_ambiance_spot_11`

will both get the same property name `HueAmbianceSpot11`

**Comment by helto4real** [comment]
@FrankBakkerNl you have any input for this?

**Comment by FrankBakkerNl** [comment]
Yes, working on it...
