### ISSUE TITLE
Does not handle beta versions of HA

### ISSUE THREAD

**Issue by mcinnes01** [net-daemon/netdaemon#882]
This method doesn't support beta version i.e. ending in .0bx

```c#
if (Version.Parse(hassVersionInfo) >= new Version(2022, 9))
{
    await AddCoalesceSupport(transportPipeline, cancelToken).ConfigureAwait(false);
}
```

**Comment by mcinnes01** [comment]
I just thought something fairly simple, i.e. just check for ".0b" before trying to parse the version, as we can assume it's a version after 09/2022 and therefore has coalesce support:

```c#
if (hassVersionInfo.Contains(".0b") 
|| Version.Parse(hassVersionInfo) >= new Version(2022, 9))
{
    await AddCoalesceSupport(transportPipeline, cancelToken).ConfigureAwait(false);
}
```

**Comment by helto4real** [comment]
Please if you want you could make a PR for this?

**Comment by mcinnes01** [comment]
I tried but the template validation no matter what I put wouldn't let me create a pr

**Comment by helto4real** [comment]
> I tried but the template validation no matter what I put wouldn't let me create a pr

That is weird. Did you fork first?

**Comment by mcinnes01** [comment]
Yeah forked it, made the change went to raise a pr, spent about 30 mins trying to satisfy the template and then tried to open a bug instead, that template also wouldn't let me create one either so I settled on an issue which didn't seem to have the template validation

**Comment by helto4real** [comment]
This issue has been resolved.
