### ISSUE TITLE
Make NetDaemonApp.cs an abstract class

### ISSUE THREAD

**Issue by addd45** [net-daemon/netdaemon#89]
## Environment

- NetDaemon release with the issue: . 35 alpha
- Last working NetDaemon release (if known): n/a
- Operating environment (Home assistant Add-on/Docker/Dev setup): docker
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```

## Additional information

Talked about this in discord awhile back and @helto4real agreed that this class should be abstract, since all app daemons that inherit *must* override InitializeAsync(). Little nuances like this make it a lot easier for the end-user to make netdaemons :)

**Comment by helto4real** [comment]
Agree, lets put it on the "todolist" :) Thanks for the reminder
