### ISSUE TITLE
Output documentation in nuget

### ISSUE THREAD

**Issue by svrooij** [net-daemon/netdaemon#905]
It appears that even though there is a lot of code documentation, that documentation is not included in the nuget packages.
To do this, you have to change the project files of the respective project(s).

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    ...
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    ...
  </PropertyGroup>
</Project>
```

This will also enable warnings for public items without comment, so to clean up the list, you might want to add this as well:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  ...
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702</NoWarn> <!-- add these to also hide the warnings during development ;CS1591;CS1573 -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS1591;CS1573</NoWarn>
  </PropertyGroup>
  ...
</Project>
```

This change will make sure that documentation like this, is included in the nuget. You’ll see that data when editing your personal netdeamon apps.
 https://github.com/net-daemon/netdaemon/blob/8382bd0c1ddd9ed1f2fc586090900b3ac4920c6f/src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs#L10-L24

**Comment by helto4real** [comment]
Great suggestion.

**Comment by svrooij** [comment]
I'll start with this issue, expect a pr soon
