### ISSUE TITLE
Error logged when ExecuteAsync not used immediately

### ISSUE THREAD

**Issue by danpowell88** [net-daemon/netdaemon#95]
## The problem

I have a helper method that determines an action to call, upon loading the app an error is logged

I am however calling ExecuteAsync further below depending on a condition so this error isn't correct

## Environment

- NetDaemon release with the issue: Latest master
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup): Docker
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#
 public async Task ToggleLights(bool on)
        {
            if (Lights != null && Lights.Any())
            {
                var lights = Entities(Lights);

                IAction? action = null;
                if (@on)
                {
                    if(!this.AllStatesAre(Lights, "on"))
                    {
                        action = lights.TurnOn();
                    }

                    StartTimer();
                }
                else if(!on)
                {
                    if (!this.AllStatesAre(Lights, "off"))
                    {
                        action = lights.TurnOff();
                    }

                    CancelTimer();
                }

                if(action != null)
                    await action.ExecuteAsync();
            }
        }
```

## Traceback/Error logs

```
[09:41:34 ERR] Missing Execute or ExecuteAsync in /data/apps/HelloWorld/HelloWorld.cs (124,30) near Entities(Lights)
```

**Comment by helto4real** [comment]
This is due to a new feature that is coming that will warn users with an error of common mistakes forgetting to call ExecuteAsync. Amazing that there are actually cases where this breaks :) You do now have to worry about the code. Your code will work as usual. Think I need some kind of pragma to remove the warning in this special case where it can not be found.

**Comment by helto4real** [comment]
Filed a feature request #96 that could deal with this. You can comment on that one to tell me what you think

**Comment by helto4real** [comment]
If you use the dev build you can now use the syntax described in #96 to supress the error log.

**Comment by helto4real** [comment]
Did not get response but a fix is released. Reopen if you find the issue still exist
